<?php

namespace AMovil\Reports\DAPU\VentasLinea\Infrastructure;

use AMovil\Reports\DAPU\VentasLinea\Domain\VentasLineaRepository;
use Illuminate\Support\Facades\DB;

class EloquentVentasLineaRepository implements VentasLineaRepository
{
    public function getByDni_Fono_Periodo($dni, $fono)
    {
        $query = "SELECT /*+ PARALLEL(8) */ 
        C.CONTD_FECHA_CONTRATO FECHA_VENTA,
        C.CONTN_NUMERO_SEC NUM_SEC,
        CD.TELEFONO LINEA,
        CASE C.CONTC_TIPO_DOC_CLIENTE
        WHEN '01' THEN 'DNI'
        WHEN '02' THEN 'RUC'
        WHEN '03' THEN 'CE'
        WHEN '04' THEN 'PASAPORTE'
        WHEN '05' THEN 'SNM'
        ELSE ''  END TIPO_DOC_CLIENTE,
        C.CONTV_NRO_DOC_CLIENTE DOCUMENTO_CLIENTE,
        UPPER(C.CONTV_NOMBRE) NOMBRES_CLIENTE,
        UPPER(C.CONTV_APE_PAT) || ' ' || UPPER(C.CONTV_APE_MAT) APELLIDOS_CLIENTE,
        SUBSTR(CD.IMEI19, 0, 14) IMEI,
        P.PEDIV_CODVENDEDOR CODIGO_VENDEDOR,
        PER.PERSV_NOMBRES NOMBRES_VENDEDOR,
        PER.PERSV_APELLIDOPATERNO APELLIDO_PATERNO_VENDEDOR,
        PER.PERSV_APELLIDOMATERNO APELLIDO_MATERNO_VENDEDOR,
        PER.PERSV_DNI DOCUMENTO_VENDEDOR,
        DECODE(PER.PERSN_IDCANAL, 1, 'DAC', 2, 'CAC', 3, 'CADENA', 4, 'PVA', 5, 'SMARTCENTER', 6, 'CCE', 7, 'TELEVENTAS', 8, 'TIENDA VIRTUAL', 9, 'CONSULTORES', 10, 'FFVV') CANAL_VENTA,
        C.CONTC_OFICINA_VENTA CODIGO_OFICINA_VENTA,
        C.CONTV_OFICINA_VENTA_DESC DESC_OFICINA_VENTA
        FROM DWS.SA_SISACT_AP_CONTRATO_DET CD
        INNER JOIN DWS.SA_SISACT_AP_CONTRATO C
        ON C.CONTN_NUMERO_CONTRATO = CD.ID_CONTRATO
        LEFT JOIN DWS.SA_SECT_OFICINA_VENTA V
        ON V.OVENC_CODIGO = C.CONTC_OFICINA_VENTA
        LEFT JOIN DWS.SA_SISACT_INFO_VENTA_SAP SAP
        ON SAP.ID_CONTRATO = C.CONTN_NUMERO_CONTRATO
        AND SAP.TIPO_DOCUMENTO = 'F'
        LEFT JOIN DWS.SA_SSAPT_PEDIDO P
        ON P.PEDIN_NROPEDIDO = SAP.NRO_DOCUMENTO
        LEFT JOIN DWS.SA_PDV_PERSONAL PER
        ON LPAD(PER.PERSV_IDVENDEDOR,15,'0') = LPAD(P.PEDIV_CODVENDEDOR,15,'0')
        WHERE CD.TELEFONO = ? --Linea sin 51
        AND C.CONTV_NRO_DOC_CLIENTE = ? --Documento
        ";

        $values = [$fono, $dni];

        /*if($periodo !== null){
            $query .= " and to_char(sale_date, 'yyyymm') = ?";
            $values[] = $periodo;
        }*/

        return DB::select(DB::raw($query), $values);
    }

    public function getPrepagoByDni_Fono_Periodo($dni, $fono)
    {
        $query = "SELECT /*+ PARALLEL(8) */ 
        P.VEPR_FECHA_REG FECHA_VENTA,
        V.DVPR_LINEA LINEA,
        CASE P.VEPR_TIPO_DOC
            WHEN '01' THEN 'DNI'
            WHEN '02' THEN 'RUC'
            WHEN '03' THEN 'CE'
            WHEN '04' THEN 'PASAPORTE'
            WHEN '05' THEN 'SNM'
            ELSE ''  END TIPO_DOC_CLIENTE,
        P.VEPR_NUM_DOC DOCUMENTO_CLIENTE,
        UPPER(P.VEPR_NOM_CLIE) NOMBRES_CLIENTE,
        UPPER(P.VEPR_APE_CLIE) APELLIDOS_CLIENTE,
        P.VEPR_PEDIDO_SINERGIA PEDIDO,
        SUBSTR(V.DVPR_SERIE, 0, 14) IMEI,
        V.DVPR_COD_MATERIAL CODIGO_EQUIPO,
        P.VEPR_COD_VEN CODIGO_VENDEDOR,
        PER.PERSV_NOMBRES NOMBRES_VENDEDOR,
        PER.PERSV_APELLIDOPATERNO APELLIDO_PATERNO_VENDEDOR,
        PER.PERSV_APELLIDOMATERNO APELLIDO_MATERNO_VENDEDOR,
        PER.PERSV_DNI DOCUMENTO_VENDEDOR,
        DECODE(PERSN_IDCANAL, 1, 'DAC', 2, 'CAC', 3, 'CADENA', 4, 'PVA', 5, 'SMARTCENTER', 6, 'CCE', 7, 'TELEVENTAS', 8, 'TIENDA VIRTUAL', 9, 'CONSULTORES', 10, 'FFVV') CANAL_VENTA,
        P.VEPR_DES_PDV DESC_OFICINA_VENTA
        FROM DWS.SA_SISACT_VENTA_PREPAGO P
        INNER JOIN DWS.SA_SISACT_DETALLE_VENTA_PREPAGO V
        ON V.DVPR_ID = P.VEPR_ID
        LEFT JOIN DWS.SA_PDV_PERSONAL PER
        ON LPAD(PER.PERSV_IDVENDEDOR,15,'0') = LPAD(P.VEPR_COD_VEN,15,'0')
        WHERE P.VEPR_ESTADO = 'P'
        AND V.DVPR_ESTADO = 'P'
        AND SUBSTR(V.DVPR_LINEA, -9) = ?
        AND P.VEPR_NUM_DOC = ?
        ";
        $values = [$fono, $dni];
        return DB::select(DB::raw($query), $values);
    }
}
