<?php

namespace AMovil\Reports\Shared\Infrastructure\Services;

use Illuminate\Support\ServiceProvider;

class LaravelReportsServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->bind(
            \AMovil\Reports\RepDetLlamadas\Domain\DetalleLlamadasRepository::class,
            \AMovil\Reports\RepDetLlamadas\Infrastructure\Repository\EloquentDetalleLlamadasRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\RepFiscalia\Domain\ReporteFiscalRepository::class,
            \AMovil\Reports\RepFiscalia\Infrastructure\Repository\EloquentReporteFiscalRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ReportLog\Domain\ReportLogRepository::class,
            \AMovil\Reports\ReportLog\Infrastructure\EloquentReportLogRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\Mtc\Suspensiones\Domain\MtcSuspensionesRepository::class,
            \AMovil\Reports\Mtc\Suspensiones\Infrastructure\Repository\LaravelMtcSuspensionesRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\RepCursado\Domain\ReporteCursadoRepository::class,
            \AMovil\Reports\RepCursado\Infrastructure\Repository\LaravelReporteCursadoRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\TramiteConsulta\Domain\TramiteConsultaRepository::class,
            \AMovil\Reports\DAPU\TramiteConsulta\Infrastructure\Repository\EloquentTramiteConsultaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\SuspensionServicio\Domain\SuspensionServicioRepository::class,
            \AMovil\Reports\DAPU\SuspensionServicio\Infrastructure\Repository\EloquentSuspensionServicioRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\Adquisiciones\Domain\AdquisicionRepository::class,
            \AMovil\Reports\DAPU\Adquisiciones\Infrastructure\Repository\EloquentAdquisicionRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\RepRecargas\Domain\ReporteRecargasRepository::class,
            \AMovil\Reports\RepRecargas\Infrastructure\EloquentReporteRecargasRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\MINEDU\RepConsumo\Domain\ReporteConsumoRepository::class,
            \AMovil\Reports\MINEDU\RepConsumo\Infrastructure\EloquentReporteConsumoRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\Visanet\Domain\VisanetRepository::class,
            \AMovil\Reports\Visanet\Infrastructure\EloquentVisanetRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\Lineas\Domain\LineaRepository::class,
            \AMovil\Reports\DAPU\Lineas\Infrastructure\EloquentLineaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\CajaArequipa\GBOtorgados\Domain\GBOtorgadosRepository::class,
            \AMovil\Reports\CajaArequipa\GBOtorgados\Infrastructure\EloquentGBOtorgadosRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\CajaArequipa\FacturaDetallada\Domain\FacturaDetalladaRepository::class,
            \AMovil\Reports\CajaArequipa\FacturaDetallada\Infrastructure\EloquentFacturaDetalladaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\FONO\Domain\FonoRepository::class,
            \AMovil\Reports\DAPU\FONO\Infrastructure\EloquentFonoRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\VentasLinea\Domain\VentasLineaRepository::class,
            \AMovil\Reports\DAPU\VentasLinea\Infrastructure\EloquentVentasLineaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\LogBiometria\Domain\LogBiometriaRepository::class,
            \AMovil\Reports\DAPU\LogBiometria\Infrastructure\EloquentLogBiometriaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\EquipoBiometria\Domain\EquipoBiometriaRepository::class,
            \AMovil\Reports\DAPU\EquipoBiometria\Infrastructure\EloquentEquipoBiometriaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DAPU\HistoricoBloqueos\Domain\HistoricoBloqueoRepository::class,
            \AMovil\Reports\DAPU\HistoricoBloqueos\Infrastructure\EloquentHistoricoBloqueoRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevolucion\ExtraccionDevolucion\Domain\ExtraccionRepository::class,
            \AMovil\Reports\ExtraccionDevolucion\ExtraccionDevolucion\Infrastructure\EloquentExtraccionRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevolucion\CargaInformeFalla\Domain\ExtraccionRepository::class,
            \AMovil\Reports\ExtraccionDevolucion\CargaInformeFalla\Infrastructure\EloquentExtraccionRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\General\RepMichaellCIANN\Domain\RepMichaellCIANNRepository::class,
            \AMovil\Reports\General\RepMichaellCIANN\Infrastructure\EloquentRepMichaellCIANNRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevolucion\TablaInteres\Domain\TablaInteresRepository::class,
            \AMovil\Reports\ExtraccionDevolucion\TablaInteres\Infrastructure\EloquentTablaInteresRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\General\FacturacionAdelantada\Domain\FacturacionAdelantadaRepository::class,
            \AMovil\Reports\General\FacturacionAdelantada\Infrastructure\EloquentFacturacionAdelantadaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevolucion\TicketReports\Domain\TicketReportRepository::class,
            \AMovil\Reports\ExtraccionDevolucion\TicketReports\Infrastructure\EloquentTicketReportRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevolucion\CarteraGobierno\Domain\CarteraGobiernoRepository::class,
            \AMovil\Reports\ExtraccionDevolucion\CarteraGobierno\Infrastructure\EloquentCarteraGobiernoRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevFija\ExtraccionDevFija\Domain\ExtraccionDevFijaRepository::class,
            \AMovil\Reports\ExtraccionDevFija\ExtraccionDevFija\Infrastructure\EloquentExtraccionDevFijaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\General\LineasMTCOsiptel\Domain\LineasMTCOsiptelRepository::class,
            \AMovil\Reports\General\LineasMTCOsiptel\Infrastructure\EloquentLineasMTCOsiptelRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DetalleTasado\Domain\DetalleTasadoRepository::class,
            \AMovil\Reports\DetalleTasado\Infrastructure\EloquentDetalleTasadoRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevolucion\MODEV\Domain\MODEVRepository::class,
            \AMovil\Reports\ExtraccionDevolucion\MODEV\Infrastructure\EloquentMODEVRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\BasesClientesPrepago\Domain\BasesClientesPrepagoRepository::class,
            \AMovil\Reports\BasesClientesPrepago\Infrastructure\EloquentBasesClientesPrepagoRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\SolicitudDatosConfirmacion\Domain\SolicitudDatosConfirmacionRepository::class,
            \AMovil\Reports\SolicitudDatosConfirmacion\Infrastructure\EloquentSolicitudDatosConfirmacionRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\GeoMarketing\Domain\GeoMarketingRepository::class,
            \AMovil\Reports\GeoMarketing\Infrastructure\EloquentGeoMarketingRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\General\BloqueoImei\Domain\BloqueoImeiRepository::class,
            \AMovil\Reports\General\BloqueoImei\Infrastructure\EloquentBloqueoImeiRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\General\ComprobantePago\Domain\ComprobantePagoRepository::class,
            \AMovil\Reports\General\ComprobantePago\Infrastructure\EloquentComprobantePagoRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\BloqueoControlReg\Domain\BloqueoControlRegRepository::class,
            \AMovil\Reports\BloqueoControlReg\Infrastructure\EloquentBloqueoControlRegRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\BloqueoControlReg\Domain\BloqueoControlRegLogRepository::class,
            \AMovil\Reports\BloqueoControlReg\Infrastructure\EloquentBloqueoControlRegLogRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\RepDetConsumoNF\Domain\DetalleConsumoNFRepository::class,
            \AMovil\Reports\RepDetConsumoNF\Infrastructure\EloquentDetalleConsumoNFRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DetallePlanes\Planes\Domain\DetallePlanRepository::class,
            \AMovil\Reports\DetallePlanes\Planes\Infrastructure\EloquentDetallePlanRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DetallePlanes\FacturacionDetallada\Domain\FacturacionDetalladaRepository::class,
            \AMovil\Reports\DetallePlanes\FacturacionDetallada\Infrastructure\EloquentFacturacionDetalladaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\DetallePlanes\ConsolidadoMinutos\Domain\ConsolidadoMinutosRepository::class,
            \AMovil\Reports\DetallePlanes\ConsolidadoMinutos\Infrastructure\EloquentConsolidadoMinutosRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevFija\TicketReports\Domain\FijaTicketReportRepository::class,
            \AMovil\Reports\ExtraccionDevFija\TicketReports\Infrastructure\EloquentFijaTicketReportRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevFija\InformesFalla\Domain\InformeFallasRepository::class,
            \AMovil\Reports\ExtraccionDevFija\InformesFalla\Infrastructure\EloquentInformeFallasRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\OltCmts\Domain\OltCmtsRepository::class,
            \AMovil\Reports\OltCmts\Infrastructure\EloquentOltCmtsRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ExtraccionDevolucion\InformesCCPP\Domain\InformeCCPPRepository::class,
            \AMovil\Reports\ExtraccionDevolucion\InformesCCPP\Infrastructure\EloquentInformeCCPPRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ReporteEsim\Domain\ReporteEsimRepository::class,
            \AMovil\Reports\ReporteEsim\Infrastructure\EloquentReporteEsimRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\MantenimientoCeldas\Mantenimiento\Domain\MantenimientoCeldaRepository::class,
            \AMovil\Reports\MantenimientoCeldas\Mantenimiento\Infrastructure\EloquentMantenimientoCeldaRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\MantenimientoCeldas\TicketReports\Domain\TicketReportRepository::class,
            \AMovil\Reports\MantenimientoCeldas\TicketReports\Infrastructure\EloquentTicketReportRepository::class
        );
        $this->app->bind(
            \AMovil\Reports\ListaExcepciones\Domain\ListaExcepcionesRepository::class,
            \AMovil\Reports\ListaExcepciones\Infrastructure\EloquentListaExcepcionesRepository::class
        );
    }
}
