<?php

namespace AMovil\Reports\DAPU\Sots\Infrastructure;

use AMovil\Reports\DAPU\Sots\Domain\DapuSotRepository;
use Illuminate\Support\Facades\DB;

class EloquentDapuSotRepository implements DapuSotRepository
{
    public function getByDocCliente(string $docCliente){
        $query = "SELECT DISTINCT B.CONTD_FECHA_CONTRATO,
            DN.DN_NUM,
            B.CONTN_NUMERO_CONTRATO,
            B.CONTN_NUMERO_SEC,
            A.PAQUETE,
            B.CONTC_OFICINA_VENTA,
            PD.PDV_CANAL,
            PD.PDV_DES,
            PD.PDV_RAZON_SOCIAL,
            M.TDOCV_DESCRIPCION TIPO_DOC_CLIENTE,
            B.CONTV_NRO_DOC_CLIENTE,
            NVL(B.CONTV_NOMBRE||' '||B.CONTV_APE_PAT||' '||B.CONTV_APE_MAT, B.CONTV_RAZONSOCIAL) NOMBRE_RAZON_SOCIAL_CLIENTE,
            B.CONTV_CODIGO_VENDEDOR,
            B.CONTV_VENDEDOR,
            S.CODSOLOT NRO_SOT,
            S.FECULTEST,
            CSC.CS_ACTIV_DATE FECHA_ACTIVACION,
            S.DIRECCION
        FROM DWS.SA_SISACT_SOLICITUD_PLAN_HFC A
        JOIN DWS.SA_SISACT_AP_CONTRATO B ON B.CONTN_NUMERO_SEC = A.SOLIN_CODIGO
        JOIN DWS.SA_SISACT_AP_CONTRATO_DET B2 ON B2.ID_CONTRATO = B.CONTN_NUMERO_CONTRATO
        JOIN DWS.SA_SISACT_INFO_VENTA_SGA C ON C.ID_CONTRATO = B.CONTN_NUMERO_CONTRATO
        JOIN DWS.SA_SOLOT S ON S.CODSOLOT = C.NRO_SOT
        AND ESTSOL IN (12, 29)-- APROBADOS, SI QUIERES ANULADOS, RECHAZADOS => COMENTAR
        LEFT JOIN DMRED.CONTR_SERVICES_CAP CSC ON CSC.CO_ID = B2.CO_ID
        LEFT JOIN DMRED.DIRECTORY_NUMBER DN ON DN.DN_ID = CSC.DN_ID
        LEFT JOIN DWS.SA_SECT_TIPO_DOCUMENTO M ON B.CONTC_TIPO_DOC_CLIENTE = M.TDOCC_CODIGO
        LEFT JOIN DWS.SA_SECT_DIRECCION EE ON A.SOLIN_CODIGO = EE.SOLIN_CODIGO -- correo
        LEFT JOIN DWA.AYF_RTM_BASE_PDV PD ON B.CONTC_OFICINA_VENTA = PD.PDV_CODIGO
        WHERE B.CONTV_NRO_DOC_CLIENTE = :doc_cliente";
        
        return DB::select(DB::raw($query), ["doc_cliente" => $docCliente]);
    }
}
